sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X4RZAA2LokcCduPJZ4mSy7zIV5hgzDFawBFJTofiKWfK4XE5aiQMGleYJGvmw8B35j3Zz0Zt3cgO/LwLjjBC6R6TwQQHjpJD2/haNYPhROTvPgwmgJCELEdnryl1OB3e36UbHI3TpuyPxq4vl58FcvGRFA4WpQk/DVx8ztVgmCJiNCbTodr/pmvGu9SrAM0Q6deNE+ZV4a4H+oUea1gTdz+S62Du0z0qt0WlG+1aUOy3zhhyTf5Jpnj7AGZvs0B2vb16JR728VdyA6YTGUJW4Mt6170/JG4qv7ONr1u7Gl7h87SeK2U4Nzm7YERjMkeguIXLlfO4yBWO60dBZCAn9imhWr9Erq5kLWENi2u/YQRgjj8/RHsIuRTjz1WiBGIhsda2iFgeO3qJAMAX7hSXU1QWs6tkNuB7ig3YObKuQ2UMDqwTtcf+SMbVeMjk2tUcQEWfAr5NXmsOvRtKiS8/T1GKvq+hjPLapMd58a8nsUt7dP2FRL8uNUUR9BIBQL55zAEybO1/j8xSRBYgOmJcHgmbub2Qfsn4PfwCAnkjlO/odhrL9AShdDj5K8+iQ2LCYYVjAMYaNjpYiF6XggfjEtFdeG/qL8xS4poPX54dp4sMBq6C5hkTANAN6YPa3xFjDJffrmK1aRxw6pmoAu7zCRNL61s0z0o/zr9jErtm9mY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/In-the-Fire-of-the-Forge-A-Romance-of-Old-Nuremberg-Volume-08_5550
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy